workflows:
  flutter-release:
    name: Flutter Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
      vars:
        PACKAGE_NAME: "com.upahar.user"   
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build App Bundle (for Play Store)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - sutirthasoor7@gmail.com
